name: myntora_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  animate_do: ^4.2.0
  dio: ^5.9.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_riverpod: ^2.6.1
  go_router: ^16.1.0
  google_fonts: ^6.3.0
  shared_preferences: ^2.5.3
  intl: ^0.19.0
  riverpod_annotation: ^2.6.1
  file_picker: ^10.3.2
  date_field: ^6.0.3+1
  modal_bottom_sheet: ^3.0.0
  multi_dropdown: ^3.0.1
  connectivity_plus: ^7.0.0

dev_dependencies:
  build_runner: ^2.5.4
  custom_lint: ^0.7.6
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.6.5
  riverpod_lint: ^2.6.5

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/google_fonts/
    - assets/images/
